baseURL = "https://mizumakes.com/"
languageCode = "en-us"
title = "MizuMakes"
theme = "PaperMod"

[params]
  description = "3D printing, engineering, and making stuff"
  author = "Shimizu"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false

[params.homeInfoParams]
  Title = "MizuMakes"
  Content = "3D printing. Engineering. Making stuff."

[[params.socialIcons]]
  name = "youtube"
  url = "https://youtube.com/@MizuMakes3D"

[menu]
[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1
[[menu.main]]
  name = "Reviews"
  url = "/reviews/"
  weight = 2
[[menu.main]]
  name = "Guides"
  url = "/guides/"
  weight = 3
[[menu.main]]
  name = "Gear"
  url = "/gear/"
  weight = 4
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5